import StyledComponentsRegistry from './lib/registry';
export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children, modal }) {
	return (
		<html lang="en">
			<head />
			<body>
				<StyledComponentsRegistry>
					{children}
					{modal}
				</StyledComponentsRegistry>
			</body>
		</html>
	);
}
